version: "3.8"
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD

  admin:
    image: dpage/pgadmin4
    ports:
      - "8000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD

  app:
    build: app
    volumes:
      - ./app:/app/
    ports:
      - "80:5000"
    environment:
      - POSTGRES_PASSWORD
